@Library('pipeline-lib') _

pipeline {
    agent any

    parameters {
        booleanParam(
            name: 'All',
            defaultValue: false,
            description: 'Runs all steps'
        )
		
		booleanParam(
			name: 'Dev',
			defaultValue: false,
			description: 'Runs dev steps'
		)

		booleanParam(
			name: 'Prod',
			defaultValue: false,
			description: 'Runs prod steps'
		)

		booleanParam(
			name: 'Deploy',
			defaultValue: true,
			description: 'Runs deploy steps'
		)
    }

    environment {
        DIR = 'api'
        USERNAME = credentials('vps-username')
        DOMAIN = credentials('vps-domain')
		API_APP_SETTINGS = 'bob-robot.api'
		IMAGE_NAME = 'bob-robot'
		PROD = 'Production'
		HOST = 'miller@sys1.clarkmiller.ca'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Load secrets') {
            when {
				anyOf {
					changeset "${DIR}/**"
					expression { return params.All || params.Prod }	
				}
			}
			steps {
                dir(DIR) {
                    loadAppsettings(API_APP_SETTINGS, DEV)
                    loadAppsettings(API_APP_SETTINGS, PROD)
                }
            }
        }

        stage('Build Docker Image') {
            when {
				anyOf {
					changeset "${DIR}/**"
					expression { return params.All || params.Prod }	
				}
			}
			steps {
				dir(DIR) {
                	echo "Building Docker image for ${DIR}..."
					buildDockerImage('Dockerfile', IMAGE_NAME, 'latest')
				}
			}
        }

		stage('Deploy Prod') {
			when {
				anyOf {
					changeset "${DIR}/**"
					expression { return params.All || params.Prod }
				}
			}
            steps {
				dir("${DIR}") { 
					sh "scp docker-compose-prod.yml ${HOST}:/home/miller/bob-robot/prod/docker-compose.yml"
                	sh "ssh ${HOST} \"cd bob-robot/prod && docker compose up -d\""
				}
            }
        }
    }
}
